apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: home-lab-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: docker-config
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: "main"
    - name: image
      type: string
    - name: version
      type: string
      description: "Version to build"
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
        kind: Task
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: "true"

    - name: update-version
      taskRef:
        name: update-version
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: version
          value: $(params.version)

    - name: build-and-push
      taskRef:
        name: docker-build
      runAfter:
        - update-version
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: docker-config
          workspace: docker-config
      params:
        - name: IMAGE
          value: $(params.image)
        - name: DOCKERFILE
          value: Dockerfile
        - name: CONTEXT
          value: .

    # - name: notify-success
    #   taskRef:
    #     name: notify
    #   runAfter:
    #     - build-and-push
    #   params:
    #     - name: message
    #       value: "Pipeline completed successfully for version $(params.version)"
    #     - name: webhook-url
    #       value: $(params.webhook-url)